version: '3.9'

services:

  observability:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: es8
    environment:
      - node-name=es8
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kib8:
    image: docker.elastic.co/kibana/kibana:8.9.1
    container_name: kib8
    environment:
      - node.name=kib8
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://es8:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=123456
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - observability

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=debug
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    networks:
      - elastic

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - elastic
    ports:
      - "9090:9090"


volumes:
  data:
    driver: local
  grafana_storage: { }

networks:
  elastic:
    driver: bridge

