spring:
  data:
    mongodb:
      uri: mongodb+srv://${USERNAME_CONNECTION}:${PASSWORD_CONNECTION}@screen-movies.nvxgk.mongodb.net/?retryWrites=true&w=majority
      database: screen-movies

omdb:
  apikey: ${OMDB_APIKEY}
  baseUrl: http://www.omdbapi.com/
