name: Java CI with Maven

on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches: [ "feature/*", "develop", "main" ]

jobs:
  Build-And-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set Maven Properties with Secrets
      run: |
        echo "USERNAME_CONNECTION=${{ secrets.USERNAME_CONNECTION }}" >> settings.xml
        echo "PASSWORD_CONNECTION=${{ secrets.PASSWORD_CONNECTION }}" >> settings.xml
        echo "OMDB_APIKEY=${{ secrets.OMDB_APIKEY }}" >> settings.xml
    - name: Build with Maven
      run: mvn clean install

    - name: Run unit tests (optional)
      run: mvn test

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Create Pull Request to Develop
      uses: peter-evans/create-pull-request@v5
      with:
        branch: ""
        title: "Feature to Develop PR"
        commit-message: "Automatic PR from feature branch"
        body: "This PR merges changes from feature/* into develop."
        delete-branch: false

